apiVersion: v1
kind: Namespace
metadata:
  name: my-operator-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-operator
  namespace: my-operator-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-operator
  namespace: my-operator-ns
spec:
  selector:
    matchLabels:
      app: my-operator
  template:
    metadata:
      labels:
        app: my-operator
    spec:
      serviceAccountName: my-operator
      containers:
        - name: operator
          image: {{image}}
          imagePullPolicy: Always

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-operator-admin
subjects:
  - kind: ServiceAccount
    name: my-operator
    namespace: my-operator-ns
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
