name: Release Jops
on:
  push:
    branches:
      - main

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 20.3.0
          native-image: true
      - run: |
          mvn install
          cp cli/target/jops-runner ./jops-linux
      - name: Upload linux binary
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: ./jops-linux

  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 20.3.0
          native-image: true
      - run: |
          mvn install
          cp cli/target/jops-runner ./jops-macos
      - name: Upload macos binary
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: ./jops-macos

  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 20.3.0
          native-image: true
      - run: |
          mvn install
          copy cli\target\jops-runner .\jops-windows.exe
      - name: Upload macos binary
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: .\jops-windows.exe