name: Release Jops
on:
  push:
    branches:
      - master

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 20.3.0
          native-image: true
      - run: java -version
      - run: |
          mvn install
